
export const PI_TOKEN_PROCESS_ID = '4hXj_E-5fAKmo4E8KjgQvuDJKAFk9P2grhycVmISDLs';
export const PI_DELEGATE_PROCESS_ID = 'cuxSKjGJ-WDB9PzSkVkVVrIBSh3DrYHYz44usQOj5yE';
export const PI_DELEGATION_ORACLE_PROCESS_ID = 'It-_AKlEfARBmJdbJew1nG9_hIaZt0t20wQc28mFGBE';
export const PI_DELEGATION_HISTORIAN = 'NRP0xtzeV9MHgwLmgD254erUB7mUjMBhBkYkNYkbNEo'
export const BOTEGA_AMM_FACTORT = "3XBGLrygs11K63F_7mldWz4veNx6Llg6hI2yZs8LKHo"

export const AUTONOMOUS_FINANCE = {
	PI_TOKEN_PROCESS_ID: PI_TOKEN_PROCESS_ID,
	PI_DELEGATE_PROCESS_ID: PI_DELEGATE_PROCESS_ID,
	PI_DELEGATION_ORACLE_PROCESS_ID: PI_DELEGATION_ORACLE_PROCESS_ID,
	PI_DELEGATION_HISTORIAN: PI_DELEGATION_HISTORIAN,
	FAIR_LAUNCH_PROCESSES: {
		APUS: "jHZBsy0SalZ6I5BmYKRUt0AtLsn-FCFhqf_n6AgwGlc",
		BOTEGA: "UcBPqkaVI7W4I_YMznrt2JUoyc_7TScCdZWOOSBvMSU",
		ACTION: "NXZjrPKh-fQx8BUCG_OXBUtB4Ix8Xf0gbUtREFoWQ2Q",
		PROTOCOL_LAND: "Wc8Rg-owsWSvrmb5XAlmSs3_4UtHo9i5ui2o9UCFuTk",
		ARIO: "rW7h9J9jE2Xp36y4SKn2HgZaOuzRmbMfBRPwrFFifHE",
		PIXL: "3eZ6_ry6FD9CB58ImCQs6Qx_rJdDUGhz-D2W1AqzHD8",
		GAME: "nYHhoSEtelyL3nQ6_CFoOVnZfnz2VHK-nEez962YMm8",
		SMONEY: "oIuISObCStjTFMnV3CrrERRb9KTDGN4507-ARysYzLE",
		WANDER: "11T2aA8M-ZcoEnDqG37Kf2dzEGY2r4_CyYeiN_1VTvU",
		LOAD_NETWORK: "Qz3n2P-EiWNoWsvk7gKLtrV9ChvSXQ5HJPgPklWEgQ0",
		NUMBER_ALWAYS_BIGGER: "X0HxJGSBzney-YLDzAtjt9Pc-c6N_1sf_MlqO0ezoeI",
		AO_STRATEGY: "t7_efxAUDftIEl9QfBi0KYSz8uHpMS81xfD3eqd89rQ",
		LIQUID_OPS: "N0L1lUC-35wgyXK31psEHRjySjQMWPs_vHtTas5BJa8"
	}
}
