
export const PI_TOKEN_PROCESS_ID = 'UcBPqkaVI7W4I_YMznrt2JUoyc_7TScCdZWOOSBvMSU';
export const PI_DELEGATE_PROCESS_ID = 'cuxSKjGJ-WDB9PzSkVkVVrIBSh3DrYHYz44usQOj5yE';
export const PI_DELEGATION_ORACLE_PROCESS_ID = 'It-_AKlEfARBmJdbJew1nG9_hIaZt0t20wQc28mFGBE';

export const AUTONOMOUS_FINANCE = {
	PI_TOKEN_PROCESS_ID: PI_TOKEN_PROCESS_ID,
	PI_DELEGATE_PROCESS_ID: PI_DELEGATE_PROCESS_ID,
	PI_DELEGATION_ORACLE_PROCESS_ID: PI_DELEGATION_ORACLE_PROCESS_ID
}
