
export const PI_TOKEN_PROCESS_ID = 'UcBPqkaVI7W4I_YMznrt2JUoyc_7TScCdZWOOSBvMSU';
export const PI_DELEGATE_PROCESS_ID = 'cuxSKjGJ-WDB9PzSkVkVVrIBSh3DrYHYz44usQOj5yE';
export const PI_DELEGATION_ORACLE_PROCESS_ID = 'It-_AKlEfARBmJdbJew1nG9_hIaZt0t20wQc28mFGBE';
export const PI_DELEGATION_HISTORIAN = 'NRP0xtzeV9MHgwLmgD254erUB7mUjMBhBkYkNYkbNEo'

export const AUTONOMOUS_FINANCE = {
	PI_TOKEN_PROCESS_ID: PI_TOKEN_PROCESS_ID,
	PI_DELEGATE_PROCESS_ID: PI_DELEGATE_PROCESS_ID,
	PI_DELEGATION_ORACLE_PROCESS_ID: PI_DELEGATION_ORACLE_PROCESS_ID,
	PI_DELEGATION_HISTORIAN: PI_DELEGATION_HISTORIAN,
	FAIR_LAUNCH_PROCESSES: {
		APUS: "jHZBsy0SalZ6I5BmYKRUt0AtLsn-FCFhqf_n6AgwGlc",
		BOTEGA: "UcBPqkaVI7W4I_YMznrt2JUoyc_7TScCdZWOOSBvMSU",
		ACTION: "NXZjrPKh-fQx8BUCG_OXBUtB4Ix8Xf0gbUtREFoWQ2Q",
		PROTOCOL_LAND: "Wc8Rg-owsWSvrmb5XAlmSs3_4UtHo9i5ui2o9UCFuTk",
		ARIO: "rW7h9J9jE2Xp36y4SKn2HgZaOuzRmbMfBRPwrFFifHE",
		PIXL: "3eZ6_ry6FD9CB58ImCQs6Qx_rJdDUGhz-D2W1AqzHD8"
	}
}
