
export const AUTONOMOUS_FINANCE_DELEGATION_ORACLE_PROCESS_ID: string = "cuxSKjGJ-WDB9PzSkVkVVrIBSh3DrYHYz44usQOj5yE"

export const AUTONOMOUS_FINANCE = {
    PERMAWEB_INDEX: {
        DELEGATION_ORACLE: AUTONOMOUS_FINANCE_DELEGATION_ORACLE_PROCESS_ID
    }
}
