export const BAZAR_PROFILE_REGISTRY_PROCESS_ID: string = "SNy4m-DrqxWl01YqGM4sxI8qCni-58re8uuJLvZPypY"

export const BAZAR = {
	PROFILE_REGISTRY: BAZAR_PROFILE_REGISTRY_PROCESS_ID,
	PIXL_TOKEN: "DM3FoZUq_yebASPhgd8pEIRIzDW6muXEhxz5-JwbZwo"
}
